# Generated by Django 5.2.6 on 2025-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
