# Generated by Django 5.2.7 on 2025-12-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('developers', models.ManyToManyField(related_name='projects', to='developers.developer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('detail_project', 'Can see detail of projects')],
            },
        ),
    ]
