# Generated by Django 5.2.7 on 2025-12-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('detail_project', 'Can see detail of projects')]},
        ),
    ]
